---
name: MacOS

on: [push]

jobs:
  build:
    runs-on: "${{matrix.os}}"
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install system dependencies
        run: |
          brew install fpc tree qt5
          export PATH="/usr/local/opt/qt/bin:$PATH"
          qmake -v
          make --version
          clang --version

      - name: Install packthing
        run: |
          sudo python3 -m pip install git+https://github.com/lamestation/packthing.git
          packthing --version

      - name: Build DMG image
        run: |
          packthing -j4 --override-version "$(basename "$GITHUB_REF")" dmg
          mv build/staging/*.dmg .
