---
name: Linux

on: [push]

jobs:
  build:
    runs-on: "${{matrix.os}}"
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
              debhelper \
              fakeroot \
              fpc \
              help2man \
              imagemagick \
              libqt5serialport5-dev \
              libudev-dev \
              lintian \
              python3-pip \
              python3-setuptools \
              qt5-default \
              tree
          qmake -v
          make --version
          gcc --version

      - name: Install packthing
        run: |
          sudo python3 -m pip install git+https://github.com/lamestation/packthing.git
          packthing --version

      - name: Build self-extracting archive
        run: |
          packthing -j4 run
          mv build/staging/*.run .

      - name: Save self-extracting archive
        uses: actions/upload-artifact@v2
        with:
          name: run
          path: "*.run"

      - name: Build Debian package
        run: |
          fakeroot packthing -j4 --override-version "0.0.0-$(basename "$GITHUB_REF")" deb
          mv build/staging/*.deb .

      - name: Save debian package
        uses: actions/upload-artifact@v2
        with:
          name: deb
          path: "*.deb"
